### ISSUE TITLE
Mislabled PS2 MW Compilers

### ISSUE THREAD

**Issue by Daniel-McCarthy** [decompme/compilers#8]
## Description 

Several MW PS2 compilers are currently labeled with an incorrect version number. 
The current naming is based on the template `mwcps2-<version_number>-<runtime_build_date>`. Currently, 4 compilers are attributed to `3.0b22` but only one has that version. Feel free to reference this table below for proof. When the compiler is run it prints the version number and runtime build dates.
![image](https://github.com/decompme/compilers/assets/4957200/7a404c8c-1cd5-48ab-afb5-f329c3a223e0)

To be changed:
- `mwcps2-3.0b22-011126` -> `mwcps2-3.0-011126`
- `mwcps2-3.0b22-020123` -> `mwcps2-3.0.1-020123`
- `mwcps2-3.0b22-020716` -> `mwcps2-3.0.3-020716`

Additionally, for the display labels, the changes would be:
- `MWCPS 3.0b22 (Built 011126)` -> `MWCPS 3.0 (Built 011126)`
- `MWCPS 3.0b22 (Built 020123)` -> `MWCPS 3.0.1 (Built 020123)`
- `MWCPS 3.0b22 (Built 020716)` -> `MWCPS 3.0.3 (Built 020716)`
- Optionally for consistency: `MWCPS 2.3` -> `MWCPS 2.3 (Built 991202)`

**Comment by mkst** [comment]
Both parts now merged, just needs decomp.me to be redeployed to pickup the change.
